# Generated by Django 4.1 on 2024-04-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SauronEye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=100)),
                ('Acqui', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')])),
                ('NiveauAcquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SauronEye.acquisition')),
            ],
        ),
    ]
