# Generated by Django 4.1 on 2024-04-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SauronEye', '0002_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=100)),
                ('Sujet', models.TextField(max_length=255)),
                ('AutresCompetenceNecessaire', models.TextField(blank=True, max_length=255, null=True)),
                ('AutresCompetenceAcquise', models.TextField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('fini', models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')])),
                ('CompetenceAcquise1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_acquise_1', to='SauronEye.competence')),
                ('CompetenceAcquise2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_acquise_2', to='SauronEye.competence')),
                ('CompetenceAcquise3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_acquise_3', to='SauronEye.competence')),
                ('CompetenceAcquise4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_acquise_4', to='SauronEye.competence')),
                ('CompetenceAcquise5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_acquise_5', to='SauronEye.competence')),
                ('CompetenceNecessaire1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_necessaire_1', to='SauronEye.competence')),
                ('CompetenceNecessaire2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_necessaire_2', to='SauronEye.competence')),
                ('CompetenceNecessaire3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_necessaire_3', to='SauronEye.competence')),
                ('CompetenceNecessaire4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_necessaire_4', to='SauronEye.competence')),
                ('CompetenceNecessaire5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_necessaire_5', to='SauronEye.competence')),
            ],
        ),
    ]
